# Generated by Django 5.2 on 2025-04-24 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Technical Inquiry', 'Technical Inquiry'), ('Pricing Inquiry', 'Pricing Inquiry'), ('Business Inquiry', 'Business Inquiry'), ('Trouble using the site', 'Trouble using the site'), ('Account Issues', 'Account Issues'), ('Other', 'Other')], max_length=254)),
                ('message', models.TextField(max_length=1024)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Requests',
            },
        ),
    ]
