# Generated by Django 5.2 on 2025-06-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
